version: '3.8'
services:
  frontend:
    build:
      context: .
      target: develop
    tty: true
    stdin_open: true
    restart: unless-stopped
    ports:
      - "4300:4300"
    working_dir: /app
    volumes:
      - "./:/app"
      - ./node_modules:/app/node_modules
    command: "npm run start"

